[General]

Background="Backgrounds/agneax-wallpaper.png"
DimBackgroundImage="0.1"
ScaleImageCropped="true"
ScreenWidth="1920"
ScreenHeight="1080"

# Blur Settings
FullBlur="false"
PartialBlur="true"
BlurRadius="60"

# Design Customisations
HaveFormBackground="false"
FormPosition="center"
BackgroundImageHAlignment="center"
BackgroundImageVAlignment="center"

MainColour="#FFFFFF"
AccentColour="#00F2FE"
BackgroundColour="#0F1219"

OverrideLoginButtonTextColour=""
InterfaceShadowSize="4"
InterfaceShadowOpacity="0.4"
RoundCorners="12"
ScreenPadding="0"

Font="Segoe UI, Inter"
FontSize=""

# Interface Behavior
ForceRightToLeft="false"
ForceLastUser="true"
ForcePasswordFocus="true"
ForceHideCompletePassword="false"
ForceHideVirtualKeyboardButton="true"
ForceHideSystemButtons="false"
AllowEmptyPassword="false"
AllowBadUsernames="false"

# Translations
HeaderText="Welcome to Agneax OS"
TranslatePlaceholderUsername="Username"
TranslatePlaceholderPassword="Password"
TranslateShowPassword="Show Password"
TranslateLogin="Login"
TranslateLoginFailedWarning="Login Failed"
TranslateCapslockWarning="Caps Lock is ON"
TranslateSession="Session"
TranslateSuspend="Suspend"
TranslateHibernate="Hibernate"
TranslateReboot="Reboot"
TranslateShutdown="Shutdown"
TranslateVirtualKeyboardButton="Virtual Keyboard"
