[LightDM]
run-directory=/run/lightdm

[Seat:*]
type=local
xtightvnc-display-width=1024
xtightvnc-display-height=768
user-session=agneax-wayland
autologin-user=agneax
autologin-user-timeout=0
autologin-in-background=false
